### ISSUE TITLE
ORA-00911: invaild character

### ISSUE THREAD

**Issue by westerntribal** [ogobrecht/d3-force-apex-plugin#20]
Hi, 
Running my sql code in the home page I keep getting 00911 error with just one node on the screen?
If i do a single record view on the column 'single_clob_result' in SQL developer from the same sql code I have in the home page and then copy that data to the clipboard and paste it into the 'Your Data' field in the playground and hit the 'set data' button it works fine ?

Data is as follows

`<data>
  <nodes ID="4715" LABEL="Parent" SIZEVALUE="5000" COLORVALUE="30"/>
  <nodes ID="7535" LABEL="Child" SIZEVALUE="2500" COLORVALUE="35"/>
  <nodes ID="7537" LABEL="Child" SIZEVALUE="2500" COLORVALUE="35"/>
  <nodes ID="7539" LABEL="Child" SIZEVALUE="2500" COLORVALUE="35"/>
  <nodes ID="7541" LABEL="Child" SIZEVALUE="2500" COLORVALUE="35"/>
  <links FROMID="4715" TOID="7535"/>
  <links FROMID="4715" TOID="7537"/>
  <links FROMID="4715" TOID="7539"/>
  <links FROMID="4715" TOID="7541"/>
</data>`

**Comment by ogobrecht** [comment]
Hi,

please have a look in the plugin code under the shared components. If somethings is going wrong here, then the error is pushed to the graph as a minimum information, that there are problems. Otherwise you would see nothing in the frontend.

Your query/data seems to be ok, but together with the processing in the plugin code there are problems. Do you have a `;`at the end of your query? If so, please remove this.

Hope, this helps.

Best regards
Ottmar

**Comment by westerntribal** [comment]
Hi Ogobrecht,
Thanks for the prompt response. 
I removed the semi colon from the end of the query on the webserver and it now works. 
So... as often is the case it was a simple thing I could not identify causing the issue. 
Thanks so much for making this plugin available and also for your time to help me get it working.

**Comment by ogobrecht** [comment]
Hi,

I think, I should remove the semi colon from the users queries in the next version, so that this type of problems is finally fixed.

Best regards
Ottmar
