### ISSUE TITLE
D3 force apex wrong node positions

### ISSUE THREAD

**Issue by Sergiu354** [ogobrecht/d3-force-apex-plugin#23]
The graph places nodes incorrect. Check the images below.
[D3 Force apex graph](https://i.stack.imgur.com/SF8Pl.png)

**Comment by ogobrecht** [comment]
Hi Sergiu,

it seems, that your query delivers no distinct data.

Please verify your query result. It is essential for the plugin to get distinct data (nodes and links), otherwise D3 has to calculate more positions then needed for double or more entries and you see often the wrong positions. For the links it is not so obvious, if you deliver non distinct data, because you normally don't see it, if a link is rendered two times or more. But here you have the same problem: D3 has to do more work then needed because of the double or more links. See also issue #17.

Hope I am right and you are able to fix your problem. Please let me know, when I can close the issue or do it by yourself.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Sergiu,

do you have any news? Can I close the issue?

Best regards
Ottmar

**Comment by Sergiu354** [comment]
Hi Ogobrecht, 
yes, everything is working. The problem was, as you said, in the SQL request.
thanks you

**Comment by ogobrecht** [comment]
Hi Sergiu,

thank you for your feedback :-)

Best regards
Ottmar
