### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined ....

### ISSUE THREAD

**Issue by Lutherwaves** [ogobrecht/d3-force-apex-plugin#24]
Hi,
I really liked your implementation of the forced graph and decided to try and test it out with some of my data. Unfortunately I stumbled upon an Uncaught TypeError when trying to load the example.html. The error:

Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.f.main.init (d3-force-2.0.3.min.js:formatted:20)
    at netGobrechtsD3Force (d3-force-2.0.3.min.js:formatted:1353)
    at window.onload ((index):29)

I tried to somehow circle around the issue but failed because of my lacking skills in JS. I would love if you could give me some feedback/tips on how to go around the bug or to solve it. 

Thanks in advance!

**Comment by ogobrecht** [comment]
Hi Lutherwaves,

sorry for the not functional example. I had to fix the Oracle APEX plugin some time ago and I forgot to check the standalone version.

During the summer I was working on the documentation with JSDoc and some improvements. Unfortunately I had to switch to some other projects and since three months I had no time to do the last steps for the new version. 

But: the new version is still running - also standalone. Please check out the "dev" branch and have a look in the "server" subdirectory. The links in the README.md to the online docs are currently not working because the new version is not finished yet. If you want to see the new docs, then please have a look in the subdirectory "docs".

Sorry again, the winter is coming and with it more time again for this project. I still hope to finish the last steps for the new release this year (2017).

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi again,

if you are not able to get the graph running please provide me your test data and I will try to see what is going on.

Best regards
Ottmar

**Comment by Lutherwaves** [comment]
Hi Ottmar,

I am really thankful for the speedy response. The project I am working on requires me to test the plugin beforehand. Thus I was looking for a working example using your provided beta data. I would be happy to wait for you to finish your work on this project and then test out my implementation.

Best regards
Martin Yankov

Sent from Mail for Windows 10

**Comment by ogobrecht** [comment]
Hi Martin,

I have a question: Do you work with Oracle APEX and using the plugin or do you want to use the bare JavaScript files in an normal HTML environment?

Can you provide me a small data sample which causes the error so I can have a look, what the reason is for your problem?

Thank you and best regards
Ottmar

**Comment by Lutherwaves** [comment]
Hi Ottmar,
I am actually trying to use the plugin in a normal HTML environment. We have an application built on Django in which I want to implement your beautiful force network graph.  

I am relying on the comment on the “.start();” line in https://ogobrecht.github.io/posts/2015-02-20-d3js-force-directed-network-chart: “sample data is provided when called without data”; to load the said “sample data” so I can initialize the example locally in my development environment. 

Would really appreciate a suggestion, perhaps I am missing something and honestly thanks again for the provided support!
Best wishes
Martin Yankov



Sent from Mail for Windows 10

**Comment by ogobrecht** [comment]
Hi Martin,

as mentioned earlier please try the current dev version: https://github.com/ogobrecht/d3-force-apex-plugin/archive/dev.zip - it is stable enough for your tests.

You will find in the `server` directory a running example.html. To get an idea which data you have to provide you can simply print the json data of the running graph to your console by executing `example.data()` or for a serialized version `JSON.stringify(example.data());`. 

For a pretty output you can use `JSON.stringify(example.data(), null, 2);`.

Please have also a look in the docs directory and launch the index.html in your browser to see the new API docs.

Hope this helps, best regards
Ottmar

**Comment by Lutherwaves** [comment]
Hi Ottmar,

I just tried it and it ran effortlessly! 
I guess I didn’t really download the dev version, as I thought earlier. 

Anyways thanks for the support, Its really appreciated!
Good luck with your future projects!

Best wishes
Martin Yankov

Sent from Mail for Windows 10
