### ISSUE TITLE
hey ogobrecht, thanks for d3 force apex. but it is really not clear how to run standalone in any html browser. i am really not getting it

### ISSUE THREAD

**Issue by lltiago** [ogobrecht/d3-force-apex-plugin#26]

**Comment by ogobrecht** [comment]
Hi,

I released a new version the last days - there was a bug with the standalone version after the last Oracle APEX plug-in fix. Sorry for that. I am not sure which version you tried - current one is 2.1.0. Please have a look at the online demo, which is a standalone implementation and currently should run fine in a up to date browser with SVG support: <https://ogobrecht.github.io/d3-force-apex-plugin/tutorial-1-getting-started.html> - this online demo is also referenced on top of the current README file in the repo.

If you put the follwing code in any HTML page, it should do the trick (don't forget to provide the referenced files ;-)

```html
<div id="example"></div><!--the graph container-->
<link  href="./d3/d3-force-2.1.0.css" rel="stylesheet" type="text/css">
<script src="./d3/d3-3.5.6.min.js"></script>
<script src="./d3/d3-force-2.1.0.min.js"></script>
<script>
  window.onload = function (){
    window.example = netGobrechtsD3Force("example")
      .debug(true) //to enable the customization wizard
      .lassoMode(true)
      //.zoomMode(true)
      .useDomParentWidth(true) //for responsive layout
      .wrapLabels(true)
      .start(); //sample data is provided when called without data
  }
</script>
```

If you download the current master branch there is also an `example.html` file provided under the `dist`subfolder - this should also run without problems when opened in a browser.

Please try again and let me know, if you are succesful or close the issue by yourself.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi again,

maybe these links are also helpful on how to push own data into your graph - I have to improve the docs for the standalone usage because the Oracle APEX plug-in users normally don'nt have to care how to provide data - they simply provide a SQL query for the data and the rest is done by the plugin...

- <https://ogobrecht.github.io/d3-force-apex-plugin/module-API.html#.start>
- <https://ogobrecht.github.io/d3-force-apex-plugin/module-API.html#.render>
- <https://ogobrecht.github.io/d3-force-apex-plugin/module-API.html#.resume>
- <https://ogobrecht.github.io/d3-force-apex-plugin/module-API.html#.data>
- <https://ogobrecht.github.io/d3-force-apex-plugin/tutorial-3-included-sample-data.html>

Hope this helps, best regards
Ottmar

**Comment by ogobrecht** [comment]
No feedback since 7 days, issue closed, outdated.
