### ISSUE TITLE
customize link

### ISSUE THREAD

**Issue by Andr700203** [ogobrecht/d3-force-apex-plugin#31]
Hello, Ottmar.

Question: how can I remove the customize link
![default](https://user-images.githubusercontent.com/42889568/46458950-184abe80-c7c0-11e8-8687-2b3f12d93081.png)

I did:
![default](https://user-images.githubusercontent.com/42889568/46459028-5fd14a80-c7c0-11e8-93a0-da260e5b4494.png)

where SERV_MODULE_CONTENT - static id region,
this does not work

Thanks,
Best regards, Andrey.

**Comment by ogobrecht** [comment]
Hi,

with `yourGraphVariable.customize(true)` you start the customization wizard. With `yourGraphVariable.customize(false)` you stop the wizard. The link to the customization wizard is only shown, when the graph is in debug mode (in the Oracle APEX plugin this mode is automatically entered, when there is an Application Builder session - end users without such an session don't see the link except you set the debug explicitly by calling `yourGraphVariable.debug(true)`. You can of course switch off the debug mode (which should never be set in an production environment because it writes many infos to the browser console) with this command: `yourGraphVariable.debug(false)`. 

Please refer also to the docs:

- https://ogobrecht.github.io/d3-force-apex-plugin/module-API.html#.debug
- https://ogobrecht.github.io/d3-force-apex-plugin/module-API.html#.customize

Best regards
Ottmar
