### ISSUE TITLE
I have been working on showing images in each node  -   Comment

### ISSUE THREAD

**Issue by pablo-flores** [ogobrecht/d3-force-apex-plugin#39]
Hi Ottmar

I have been working on showing images in each node, I could do it with link in this way

apex_util.prepare_url (: APP_IMAGES || 'icons8-server-100.png') as image

but not so with images that are in a blob field in a table

(Select decode (nvl (dbms_lob.getlength (IMAGE2), 0), 0, null, apex_util.get_blob_file_src ('P62_IMAGEN', IDIMAGEN)) IMAGE2 from MY_IMAGENES where IDIMAGEN = 1) as image

What can I do to achieve it?

thank you very much for your help.

**Comment by ogobrecht** [comment]
Hi Pablo,

this has nothing to do with the D3 plugin. Please have a look at the following posts - maybe these are helpful:

- http://dgielis.blogspot.com/2009/05/using-apexutilgetblobfilesrc-on-public.html
- https://joelkallman.blogspot.com/2014/03/yet-another-post-how-to-link-to.html
- https://stackoverflow.com/questions/29486663/oracle-apex-display-blob-images-directly-in-a-report

**Comment by pablo-flores** [comment]
Excellent Ottmar !

it worked with 

apex_util.get_blob_file_src ('P32_IMAGEN2', id) as image

thanks for your help !
best regards
Pablo

**Comment by ogobrecht** [comment]
Hi Pablo,

I definitely recommend to read Joels blog posting: https://joelkallman.blogspot.com/2014/03/yet-another-post-how-to-link-to.html

Although your solution is working you may get performance issues because of to o many reuests to your images. Think about client side caching by setting the correct headers - therefore have a look at Joels posting.

Best regards
Ottmar
