### ISSUE TITLE
Apex application crashing on IE11/EDGE

### ISSUE THREAD

**Issue by Peachman97** [ogobrecht/d3-force-apex-plugin#41]
Hi There,

Just wondering if there is any compatibility issues with using this with IE11/Edge and this plugin? I am able to work the example apex page in chrome, but when i trigger an event the page freezes, crashes and reloads. I have tried to load the debugger for errors however none are thrown and it just crashes.

Thanks

Ryan

**Comment by ogobrecht** [comment]
Hi Ryan,

sorry for my late answer.

There were problems in the past with SVG rendering in IE 9-11 - but for this a workaround is implemented since a long time.

Please provide more informations: 

- Did you install the sample app on your own environment?
- Do you use an own app only with my plugin?
- What have you tried in detail?
- Did you use one of the API methods?
- Do you have a code example, which is not working?

It is always hard to answer questions with not enough details. Can you create an app on apex.oracle.com? If you have the error also there, please give me access and I will try to find your problem.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Ryan,

I close the issue now because of inactivity. Please feel free to reopen it when your issue still exists and you have more details for me.

Best regards
Ottmar
